# backend/Dockerfile
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY main.py .

# Make a directory for storing .vtu outputs
RUN mkdir data_output

EXPOSE 5000
CMD ["python", "main.py"]