version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - storage:/app/storage
    ports:
      - "5000:5000"

  frontend:
    build:
      context: ./frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    volumes:
      - storage:/app/storage

volumes:
  storage:
