FROM stefanofochesatto/viamr:latest

WORKDIR /app

# Copy application files
COPY backend.py requirements.txt /app/

# Install Python's virtual environment package
RUN apt-get update && apt-get install -y python3-venv

# Create and activate a virtual environment
RUN python3 -m venv venv
ENV PATH="/app/venv/bin:$PATH"

# Install dependencies within the virtual environment
RUN pip install --no-cache-dir -r requirements.txt

CMD ["python", "backend.py"]
