FROM stefanofochesatto/viamr:latest

# Set the working directory for app files
WORKDIR /app

# Copy application files
COPY backend.py requirements.txt /app/

# Activate the custom Python environment and install extra dependencies
RUN bash -c "source /firedrake/bin/activate && pip install -r /app/requirements.txt"

# Set the command to activate the environment and run the backend
CMD ["bash", "-c", "source /firedrake/bin/activate && python /app/backend.py"]
