FROM stefanofochesatto/viamr:latest

# Set the working directory
WORKDIR /app

# Copy application files
COPY backend.py requirements.txt /app/

# Activate the custom environment and install extra dependencies
RUN bash -c "source firedrake/bin/activate && pip install -r requirements.txt"

# Set the command to activate the environment and run the backend
CMD ["bash", "-c", "source firedrake/bin/activate && python backend.py"]
